### ISSUE TITLE
Skin rendering is not stripping alpha correctly

### ISSUE THREAD

**Issue by NickAcPT** [Statsify/statsify#451]
### Which package is this bug report for?

@statsify/assets skin-renderer

### Issue description

I use a mod that reads some data encoded in the alpha channel of certain regions of the skin. Minecraft by default strips the alpha of certain regions (along with doing other tasks) while loading the skin.

I found this issue by looking up a render of my skin with `/skin NickAc`.
I have browsed the source-code for a bit to try and PR a fix but it seems that the rendering part is private 🙄 (gotta love it when people claim to be open-source then failing to be so).

<details>
<summary>The render from Statsify</summary>
![image](https://cdn.discordapp.com/attachments/1039930993873780746/1039930993991229503/skin.png)
</details>

<details>
<summary>How the skin is expected to look</summary>
![image](https://i.imgur.com/VzMnOvE.png)
</details>

**Comment by eatmyvenom** [comment]
Since this has come up before I will write up a huge essay explanation for this.

## This as an issue on GitHub
We have the bug reporting section in the discord for a reason, use it and be patient. 

> This is a repost from the Discord server since I have reported the bug and it has not been addressed nor it has been acknowledged.

We are all working on this at our own convenience, we owe you nothing and promise nothing. The reason it has not been addressed is because we are all busy and have not had time to look into the issue at hand.  Your skin acting up in the discord bot is not a huge issue and will have to wait.

## What is really going on
Well our skin renderer is a rollup bundle of the project [skinview3d](https://github.com/bs-community/skinview3d). This project is a "Three.js powered Minecraft skin viewer." which is for web browsers. In case you are unaware, web browsers commonly have some rendering features in them that are not available in Node.js such as OpenGL. Due to this we have some weird polyfills to allow it to work in Node.js and with [skia-canvas](https://github.com/samizdatco/skia-canvas). One of the tools used is called [node-canvas-webgl](https://www.npmjs.com/package/node-canvas-webgl). All of these parts just tossed together is not really a good way of doing things but it has not been a priority issue at all.

Due to skinview3d not being our project, it is not really a good idea for us to host a frankensteined version of their source code, even as a fork since it is not a good representation of their project. Also since our usage is out of their intended scope we don't want to have people directing issues with our skin renderer to them which is what you would have most likely done.

Another thing I would like to address is things we do not share. First of all, we have a very nice designer who also generates all of the background images for us. We agree with him that since these take quite a bit of effort for him to create, we won't share them with the public. This also helps us ensure are no direct clones of the bot while people can still contribute or see how we do most of the things we do. Since we have this private part that we work with, it seemed to be a good place to leave the skin renderer so people new to the project would not have to deal with getting it to run when working on other parts of the project.

## So called "failing" to be open source
> gotta love it when people claim to be open-source then failing to be so

Well you have known this
![image](https://user-images.githubusercontent.com/42223931/203012003-8e712092-b1e8-4a77-b6f6-4df069fb4677.png)

And we provided a reason
![image](https://user-images.githubusercontent.com/42223931/203012170-38de0ae0-c10b-41a3-8131-c2090463ab70.png)

So you already know exactly why this is hosted in the way that it is. You also could have simply asked us what the skin renderer is based on or anything like that. We don't have a banner everywhere screaming "open source" we have a GitHub repo with all of the relevant code for this project. We didn't create the skin renderer, simply repurposed it for usage on a server and therefore don't host it as our source code.

I also am curious as to why you opened this issue when you are already all aware of everything here. The only wording you changed is adding "gotta love it when people claim to be open-source then failing to be so" on the repo with all of the source code for the bot and the API.

### More research is your friend
![image](https://user-images.githubusercontent.com/42223931/203012787-7da1565b-4d15-43a2-8968-dff9d1b38de2.png)
![image](https://user-images.githubusercontent.com/42223931/203012842-0455ae2f-4ed7-4881-9036-8eced27297e6.png)
![image](https://user-images.githubusercontent.com/42223931/203012886-c3735f4d-d16c-46d7-abd5-2b07ed59bd61.png)

## A solution 
Well there is no solution to your impatience or your issues with us not hosing a huge rollup output file. We realistically will most likely not fix this issue unless we can find it easily. The only true solution is to rewrite the skin renderer and even better would be doing so without OpenGL but that's also a huge undertaking and is going to be a very far into the future project. There has been some [attempts made](https://github.com/eatmyvenom/statsify/tree/feat/skin-renderer/packages/skins) but it is not something we want to be supporting people struggling with when we can just have people use a better solution if they wish to contribute.

### I will be closing this issue since it should not be here, all user bug reports are to be kept in discord and this will not be an exception. All conversation will continue [in discord](https://discord.com/channels/692521100650741781/1039930993873780746/1044184379339055106)
